### PR TITLE
Do not persist changes when cancelling inline-edit changes in sw-data-grid component

### PR DESCRIPTION
**Pull request by theErikss0n**
### 1. Why is this change necessary?

When the inline-edit is canceled [an event gets emitted](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/index.js#L432) which is used to [save the inline-edit](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/index.js#L425). The [event is caught](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid-inline-edit/index.js#L60) and [re-emitted](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid-inline-edit/index.js#L68) by the edit component and the grid [assigns the value](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/sw-data-grid.html.twig#L206).

Expected behavior: Cancel action discards new value
Actual behavior: Cancel action assigns new value to grid

### 2. What does this change do, exactly?
This PR fixes this by not throwing the `inline-edit-assign` event when cancelling the inline-edit.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create `sw-data-grid` with `allowInlineEdit` and `showActions` set to `true` 
2. Create at least one column with the `inlineEdit` property set to any valid value (e.g. `number`)
2. Double click on the data field and edit the value
3. Click on cancel
4. New value is assigned to the data field

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by hanneswernery** [comment]
1) Please check the spelling. I.e. Uppercase the beginning of a sentence 😉 

2) When referencing a property or component name, use hilighting: `true`, `allowInlineEdit`, `onClickCancelInlineEdit(item)`

3) (in "1.") Similar to _"Expected behaviour"_, add _"Actual behavior"_. E.g. "Actual behaviour: New value is assigned anyway."

4) (in "2.") Improve the description and use of github references so it is easier to _read_ and understand what is going on. Try something like this:

When the inline-edit is canceled [an event used to be emitted](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/index.js#L432) which is also used when the [inline-edit is saved](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/index.js#L425). The [event is caught](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid-inline-edit/index.js#L60) and [re-emitted](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid-inline-edit/index.js#L68) by the edit component and the grid [assigns the value](https://github.com/shopware/platform/blob/64f4d40d17299d569aa8bae58a04af72ce3ae131/src/Administration/Resources/administration/src/app/component/data-grid/sw-data-grid/sw-data-grid.html.twig#L206). That way the new value is assigned in both the _cancel_ and the _save_ actions.
This PR fixes this by not throwing the `inline-edit-assign` event when cancelling the inline-edit.

5) (in "3.") Add a "5." step for the reproduction of the problem that names the problem. E.g. "5. New value is now assigned to the row"

**Comment by hanneswernery** [comment]
Looks good to me. Maybe @fixpunkt will have another look.

Afterwards you can close this PR, add a new PR agains `shopware` and copy the text of this draft.

**Comment by fixpunkt** [comment]
Nice work! 👏 

Description remarks:
- The description should properly explain which part of the system this affects. "inline-edit" is not quite sufficient here, you should probably start of with the fact that you're talking about the grid component .

Code:
- Did you grep for other events starting with `inline-edit-`? My intuition is that there _might be_ an event which is expected to be fired when cancelling inline editing and the line you're changing just uses the wrong one.
- Are there any pre-existing unit or e2e tests covering this component?

**Comment by fixpunkt** [comment]
shopware/platform PR: https://github.com/shopware/platform/pull/210

**Pull request closed without merging**
